### ISSUE TITLE
Waiting some of the group members to complete 1st and 2nd Iterations Planning for 1st Release (60 pts.)

### ISSUE THREAD

**Issue by Universesboy** [DavDeDev/mms#14]
link: https://docs.google.com/document/d/1KEv_Dz84uKqhvKpk2ntlZWtJHyav7RHMTZ8p0DaPKfY/edit?tab=t.0

**Comment by Mehar018** [comment]
I have updated the 1st and 2nd Iterations planning  - https://docs.google.com/document/d/1KEv_Dz84uKqhvKpk2ntlZWtJHyav7RHMTZ8p0DaPKfY/edit?tab=t.0
