### ISSUE TITLE
Project Planning and Management - 2nd Release 

### ISSUE THREAD

**Issue by Universesboy** [DavDeDev/mms#31]
Hi guys the Project Planning and Management - 2nd Release is provided below I've finished versions 1.0 and 2.0 already. Please select the remaining portion, finish the task, and provide your name. 
link: https://docs.google.com/document/d/1fXehlffKRIkIXmFv5hyLarHEV3CESz4SMPc1d1ujBcc/edit?usp=sharing

**Comment by Mehar018** [comment]
I've update the document. 
link - https://docs.google.com/document/d/1fXehlffKRIkIXmFv5hyLarHEV3CESz4SMPc1d1ujBcc/edit?tab=t.0
